### ISSUE TITLE
Temp Key

### ISSUE THREAD

**Issue by fahdmirza** [3750gustavo/AI-Writing-Notebook-UI#2]
Hi,
 I want to review this tool for my channel https://www.youtube.com/@fahdmirza , but I don't have the infermatic key, is there a way to get the temp key to do a demo? Thanks.

**Comment by 3750gustavo** [comment]
Sorry I can't, but I might look into how to implement some sort of support to kobold API, so that any user can use the app with a local model running on koboldcpp, but seem like something weird to do, if the user has access to koboldcpp, it had most of my features and more, my app was made with focus on fixing the fact that no other notebook app was working with infermatic API.

In theory any other API services that uses an API address + api_key should work with my app if you change those things on my code, (change the URL and the key inside the `config.json`), but I can't guarantee, also my app is made for text completion, so if an API works only with chat completion, even if worked, you would get subpar results.

What other API services do you have? Gemini? I believe Gemini offers a free API key, I could look onto how to add gemini support if you wanted that.

**Comment by 3750gustavo** [comment]
The only reason my app won't support kobold as of right now is because Kobold API has no key field, only address, I would have to change that in my code to work differently if Kobold was being used.

**Comment by fahdmirza** [comment]
Sure Gemini or openai should be good. thanks.

**Comment by 3750gustavo** [comment]
It should work with those already, just need to change the API url, but I might need to add support to disabling settings just to make sure

**Comment by 3750gustavo** [comment]
OpenAI might return an error as it does not support Min p and my app sends min_p always.

**Comment by 3750gustavo** [comment]
If I were to focus on Gemini or OpenAI, which one do you think would be better for you? I just looked into Gemini website and seems easier to implement it, their website is more friendly, and Gemini offers API for free.

**Comment by fahdmirza** [comment]
Sure Gemini is fine. Thanks.

**Comment by 3750gustavo** [comment]
I might take a day or two to implement the support, I will try to implement the hard way, I can't use google library to help me out, otherwise my app will get bloated with lots of things for users to install, I am trying to understand how Sillytavern managed to implement Gemini support on their system without the Google library, using AI to help me convert their JS code to my use case (request + sseclient)

**Comment by 3750gustavo** [comment]
I gonna test it out with a free key I got from gemini, so this way I can be sure it should work on yours once its done.

**Comment by 3750gustavo** [comment]
> Sure Gemini is fine. Thanks.

Are you willingly to wait? This is my first big project I made, I want to make sure this integration is well done, that is not something made poorly, I will probaly add a `USE_GEMINI` to my config json the same way I added a toggle for NovelAI voice, it will come disabled by default, anyone that wants to use Gemini, should only change that from false to true, like this:
```json
{
    "INFERMATIC_API_KEY": "your_api_key_here",
    "USE_TTS": false,
    "NOVELAI_API_KEY": "your_novelai_key_here",
    "USE_GEMINI": true
}
```

**Comment by 3750gustavo** [comment]
I will make so if USE_GEMINI is true, the infermatic key becomes the Gemini Key, and it will automaticly use the url from gemini instead of infermatic

**Comment by fahdmirza** [comment]
Sure mate, take your time. No rush. Thanks.

**Comment by 3750gustavo** [comment]
sorry, I could not find a way to use Gemini without using their library, also even if I had managed to, while reading their docs I discovered their API does not support text completion, only chat completion, so it would be incompatible with my app anyway, my best bet now would be to focus on adding support to using the API for a local model through koboldcpp, this type of support would also open doors to running a model on Google collab for free and use that api and address on my app, can I close this issue, or will you want me to try the local model option?

PS: this is already going out of the original scope of this project, that is to be an app mainly focused on infermatic users.

**Comment by fahdmirza** [comment]
All good mate. Up to you if you want to close the issue. Great effort though, thanks.
